# This is a basic workflow to help you get started with Actions

name: CI
env:
  EXAMPLE: ${{ secrets.EXAMPLE }}

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ci"
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'
          node-version: '16'

      - name: 'Install the dependencies'
        run: 'yarn install --immutable'

      - name: 'Lint the code'
        run: 'yarn lint'

      - name: 'Add lint summary'
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: 'Compile the app'
        run: yarn tsc
